window.InOrdineNative=window.InOrdineNative||null;
(function(){
const css=`
/* 04/10/2026 — stile Todo definitivo, leggero e semanticamente multicolore. */
#todoHub .todoHubCard.pending,#todoHub .todoHubCard.completed{min-height:220px!important;padding:16px!important;border:1px solid #c8e9d8!important;background:radial-gradient(circle at 23% 22%,rgba(61,203,147,.10) 0 34px,transparent 35px),radial-gradient(circle at 78% 42%,rgba(61,203,147,.08) 0 18px,transparent 19px),linear-gradient(155deg,#fff 0 58%,#f1fbf6 59% 100%)!important;overflow:hidden!important}
#todoHub .todoHubCard.pending:after,#todoHub .todoHubCard.completed:after{content:"";position:absolute;left:-12%;right:-12%;bottom:28px;height:62px;pointer-events:none;background:linear-gradient(168deg,transparent 0 24%,rgba(45,190,137,.08) 25% 35%,transparent 36% 51%,rgba(45,190,137,.06) 52% 61%,transparent 62%)}
#todoHub .todoHubCard.pending>span:first-child,#todoHub .todoHubCard.completed>span:first-child{padding-top:92px!important;position:relative;z-index:2}
#todoHub .todoHubPerson{top:15px!important;right:15px!important;width:46px!important;height:46px!important;z-index:3}#todoHub .todoHubPerson img{width:46px!important;height:46px!important;border-radius:10px!important}
#todoHub .todoHubCard.pending .chev{background:#fff2d9!important;color:#c98016!important;border:1px solid #f1d7a7!important}#todoHub .todoHubCard.completed .chev{background:#e2f5e9!important;color:#148050!important;border:1px solid #c9e9d7!important}
#todoHub .todoHubCard.notify .icon,#todoHub .todoHubCard.notify .chev{background:#e7f4ff!important;color:#167fc5!important}#todoHub .todoHubCard.config .icon,#todoHub .todoHubCard.config .chev{background:#f0ebff!important;color:#7657c4!important}#todoHub .todoHubCard.reopen .icon,#todoHub .todoHubCard.reopen .chev{background:#e6f7f3!important;color:#138b78!important}
#todoHub .todoHubCard.notify,#todoHub .todoHubCard.config,#todoHub .todoHubCard.reopen{border-color:#e0ece6!important;background:#fff!important}
#todoActive .todoHero,#todoDone .todoHero{background:#fff!important;border-color:#d8ebe1!important}#todoActive .todoFilterAll.active,#todoDone .todoFilterAll.active{background:#178f63!important;border-color:#178f63!important}
#todoActive .todoTaskRow,#todoDone .todoDoneRow{background:#fff!important;border-color:#e3ece7!important}#todoActive .todoNotifyBtn,#todoActive .todoNotifyToggle{background:#e7f4ff!important;color:#157fc5!important;border:1px solid #d1e8f7!important}#todoActive .todoNotifyBtn.on,#todoActive .todoNotifyToggle.on{background:#fff1d8!important;color:#c77d10!important;border-color:#f1dab0!important}
#todoActive .todoCompleteBtn{background:#fff!important;color:#234b36!important;border:1px solid #cfe5d8!important;box-shadow:none!important;font-weight:800!important}#todoActive .todoCompleteCircle{border-color:#198857!important;background:#fff!important}#todoActive .todoTaskEditCard.overdue{border-left:4px solid #d84b56!important}#todoActive .todoTaskEditCard.overdue small{color:#c13d47!important}
#todoDone .todoDoneStatus{background:#e2f4e8!important;color:#177b4b!important;border:1px solid #cfe8d8!important}#todoDone .todoDoneRow:nth-child(4n+1){border-left:4px solid #4a90d9!important}#todoDone .todoDoneRow:nth-child(4n+2){border-left:4px solid #7a5ac8!important}#todoDone .todoDoneRow:nth-child(4n+3){border-left:4px solid #e09b26!important}#todoDone .todoDoneRow:nth-child(4n+4){border-left:4px solid #1a9a78!important}
/* 20 Impostazioni */
#todoSettings .todoHero.settings{min-height:94px!important;padding:18px 16px 16px 82px!important;background:#fff!important;border:1px solid #bfe6d1!important;box-shadow:0 5px 15px rgba(25,103,69,.05)!important}#todoSettings .todoHero.settings .todoHeroArt{left:16px!important;right:auto!important;top:19px!important;width:52px!important;height:52px!important}#todoSettings .todoHero.settings .todoHeroArt img{width:52px!important;height:52px!important;border-radius:12px!important}#todoSettings .todoHero.settings strong{font-size:17px!important;color:#153729!important}#todoSettings .todoHero.settings small{font-size:11px!important;line-height:1.35!important;color:#6f8177!important}
#todoSettings .todoSettingsStack{gap:8px!important;margin-top:11px!important}#todoSettings .todoSettingCard{min-height:63px!important;padding:9px 12px!important;border-color:#dcebe3!important;background:#fff!important;box-shadow:0 3px 10px rgba(32,83,59,.035)!important}#todoSettings .todoSettingCard .i{width:36px!important;height:36px!important;display:grid!important;place-items:center!important}
#todoSettings .todoSettingCard:nth-of-type(1) .i{background:#f0ebff!important;color:#7657c4!important}#todoSettings .todoSettingCard:nth-of-type(2) .i{background:#e5f7f2!important;color:#148d78!important}#todoSettings .todoSettingCard:nth-of-type(3) .i{background:#e7f4ff!important;color:#167fc5!important}#todoSettings .todoSettingCard:nth-of-type(4) .i{background:#fff0dc!important;color:#cc7d13!important}#todoSettings .todoSettingCard:nth-of-type(5) .i{background:#eee9ff!important;color:#694eb4!important}#todoSettings .todoSettingCard:nth-of-type(6) .i{background:#e7f4ff!important;color:#167fc5!important}
/* Modali Todo 19-24 */
.modal.todoSettingsModal{background:rgba(7,35,25,.24)!important}.modal.todoSettingsModal .modalCard{background:linear-gradient(165deg,transparent 0 82%,rgba(66,199,146,.07) 83% 88%,transparent 89%),linear-gradient(180deg,#fcfffd,#f4fbf7)!important;border:1px solid #d6ebe0!important;box-shadow:0 18px 44px rgba(18,75,49,.14)!important}.modal.todoSettingsModal .modalHead{border-bottom:1px solid #e2eee7!important;padding-bottom:10px!important}.modal.todoSettingsModal .modalTitle{color:#163b2d!important;font-size:24px!important}.modal.todoSettingsModal .close{background:#e9f6ef!important;color:#167453!important}
.modal.todoSettingsModal .todoThemeIntro{border:1px solid #bfe7d1!important;background:linear-gradient(135deg,#fff,#f0fbf5)!important;box-shadow:0 4px 12px rgba(25,103,69,.045)!important}.modal.todoSettingsModal .todoThemeIntro img{width:52px!important;height:52px!important;border-radius:12px!important}.modal.todoSettingsModal .modalBtns{position:sticky!important;bottom:0!important;padding:10px 0 2px!important;background:linear-gradient(180deg,rgba(244,251,247,0),#f4fbf7 28%)!important;gap:9px!important}.modal.todoSettingsModal .modalBtns .btn{background:#168c60!important;color:#fff!important;box-shadow:none!important}.modal.todoSettingsModal .modalBtns .btn.secondary{background:#fff!important;color:#486458!important;border:1px solid #d6e6dd!important}
/* 19 Notifiche */
.modal.todoNotificationsModal .settingsSubRow{background:#fff!important;border:1px solid #dceae3!important;border-radius:14px!important;margin:7px 0!important}.modal.todoNotificationsModal .settingsSubRow .settingsRowIcon{background:#e7f4ff!important;color:#167fc5!important}.modal.todoNotificationsModal .card{background:#fff!important;border:1px solid #dceae3!important;border-radius:16px!important;box-shadow:none!important}.modal.todoNotificationsModal .settingsTitle{font-size:12px!important;letter-spacing:.5px!important;text-transform:uppercase!important;color:#598071!important}.modal.todoNotificationsModal .field{margin:10px 0!important}.modal.todoNotificationsModal .field label{color:#315648!important;font-size:11px!important}.modal.todoNotificationsModal select,.modal.todoNotificationsModal input[type="time"],.modal.todoNotificationsModal input[type="number"]{border-color:#d9e8e0!important;background:#fbfdfc!important}
.todoRecentSection{margin:11px 0 2px}.todoRecentTitle{font-size:11px;font-weight:900;color:#5d796d;letter-spacing:.5px;margin:0 4px 6px}.todoRecentRow{display:grid;grid-template-columns:32px minmax(0,1fr) 18px;gap:8px;align-items:center;min-height:47px;padding:7px 9px;border-bottom:1px solid #e7efea;background:#fff}.todoRecentRow:first-of-type{border-radius:13px 13px 0 0}.todoRecentRow:last-child{border-radius:0 0 13px 13px;border-bottom:0}.todoRecentIcon{width:30px;height:30px;border-radius:50%;display:grid;place-items:center;background:#e8f4ff;color:#167fc5;font-size:15px}.todoRecentRow:nth-child(3) .todoRecentIcon{background:#f0ebff;color:#7456bd}.todoRecentRow:nth-child(4) .todoRecentIcon{background:#fff0dc;color:#c98217}.todoRecentRow strong{display:block;font-size:11px;color:#203e32}.todoRecentRow small{display:block;font-size:9px;color:#7b8d84;margin-top:2px}.todoRecentArrow{color:#86a296}
/* 21 Tema */
.modal.todoThemeModal .todoThemeOption{grid-template-columns:76px minmax(0,1fr) 26px!important;min-height:82px!important;padding:9px 10px!important;background:#fff!important;border-color:#dceae3!important}.modal.todoThemeModal .todoThemeOption.active{background:#f5fcf8!important;border-color:#6ac79d!important}.modal.todoThemeModal .todoThemeIcon{width:68px!important;height:62px!important;border-radius:10px!important;font-size:0!important;border:1px solid #d7e7df!important;box-shadow:none!important;position:relative!important;overflow:hidden!important}.modal.todoThemeModal .todoThemeOption:nth-child(1) .todoThemeIcon{background:linear-gradient(180deg,#f9fffb 0 16%,#dff4e8 17% 22%,#fff 23% 100%)!important}.modal.todoThemeModal .todoThemeOption:nth-child(2) .todoThemeIcon{background:linear-gradient(180deg,#13231b 0 16%,#294a38 17% 22%,#1d3026 23% 100%)!important}.modal.todoThemeModal .todoThemeOption:nth-child(3) .todoThemeIcon{background:linear-gradient(90deg,#f8fdf9 0 50%,#1d3026 50% 100%)!important}.modal.todoThemeModal .todoThemeIcon:after{content:"";position:absolute;left:9px;right:9px;top:22px;height:6px;border-radius:4px;background:currentColor;opacity:.18;box-shadow:0 11px 0 currentColor,0 22px 0 currentColor}
/* 22 Colore */
.modal.todoColorModal .todoColorChoice{min-height:58px!important;border-color:#dceae3!important;background:#fff!important}.modal.todoColorModal .todoColorChoice.active{background:#f5fcf8!important;border-color:#6ac79d!important}.modal.todoColorModal .todoColorPreview{border-color:#dceae3!important;background:#fff!important}
/* 23 Backup */
.modal.todoBackupModal .settingsSubMenu,.modal.todoPrivacyModal .settingsSubMenu{display:flex!important;flex-direction:column!important;gap:7px!important}.modal.todoBackupModal .settingsSubRow,.modal.todoPrivacyModal .settingsSubRow{margin:0!important;background:#fff!important;border:1px solid #dceae3!important;border-radius:14px!important;min-height:58px!important}.modal.todoBackupModal .settingsRowIcon.iPurple{background:#efeaff!important;color:#7358bd!important}.modal.todoBackupModal .settingsRowIcon.iBlue,.modal.todoPrivacyModal .settingsRowIcon.iBlue{background:#e7f4ff!important;color:#167fc5!important}.modal.todoBackupModal .settingsRowIcon.iGreen,.modal.todoPrivacyModal .settingsRowIcon.iGreen{background:#e2f5e9!important;color:#168151!important}.modal.todoBackupModal .settingsRowIcon.iOrange,.modal.todoPrivacyModal .settingsRowIcon.iOrange{background:#fff0dc!important;color:#c98217!important}.modal.todoBackupModal .settingsRowIcon.iRed{background:#ffe8e9!important;color:#c73b46!important}
.todoLastBackupRow,.todoPrivacyInfoRow{display:grid;grid-template-columns:38px minmax(0,1fr) auto;gap:10px;align-items:center;min-height:58px;padding:9px 11px;background:#fff;border:1px solid #dceae3;border-radius:14px}.todoLastBackupRow .ico,.todoPrivacyInfoRow .ico{width:34px;height:34px;border-radius:50%;display:grid;place-items:center;background:#e7f4ff;color:#167fc5;font-weight:900}.todoLastBackupRow strong,.todoPrivacyInfoRow strong{display:block;font-size:12px;color:#203f32}.todoLastBackupRow small,.todoPrivacyInfoRow small{display:block;font-size:9px;color:#7b8d84;margin-top:2px}.todoLastBackupRow time{font-size:9px;color:#568272;font-weight:800}.todoBackupExtras{margin-top:10px;padding-top:9px;border-top:1px dashed #d7e7df}.todoBackupExtrasTitle{font-size:10px;font-weight:900;color:#7a8c84;margin:0 3px 6px;text-transform:uppercase;letter-spacing:.5px}
`;
const $=id=>document.getElementById(id);
const hero=(title,copy)=>{const b=$('modalBody');if(!b||b.querySelector('.todoMasterHero'))return;const h=document.createElement('div');h.className='todoThemeIntro todoColorIntro todoMasterHero';h.innerHTML='<img src="assets/eds-green-approved.png" alt=""><div><strong>'+title+'</strong><small>'+copy+'</small></div>';b.prepend(h)};
const settings=()=>{const s=$('todoSettings');if(!s||s.classList.contains('hidden'))return;const t=$('todoSettingsGreeting');if(t)t.textContent='Personalizza la tua esperienza';const x=s.querySelector('.todoHero.settings small');if(x)x.textContent='Gestisci le impostazioni della sezione Cose da fare.'};
const notifications=()=>{const m=$('modal'),b=$('modalBody'),n=$('todoGlobalNotify');if(!m||!b||!n)return;m.classList.add('todoSettingsModal','todoNotificationsModal');const r=n.closest('.settingsSubRow');if(r){const a=r.querySelector('strong'),c=r.querySelector('small'),i=r.querySelector('.settingsRowIcon');if(a)a.textContent='Notifiche attive';if(c)c.textContent='Ricevi promemoria per le tue attività';if(i)i.textContent='🔔'}const card=b.querySelector('.card');if(card){const st=card.querySelector('.settingsTitle');if(st)st.textContent='Promemoria';const f=$('todoGlobalRuleTiming')?.closest('.field');if(f&&f.querySelector('label'))f.querySelector('label').textContent='Anticipo promemoria'}if(!b.querySelector('.todoRecentSection')){let a=[];try{const s=JSON.parse(localStorage.getItem('inOrdineContiV1')||'{}');a=(s.todo?.tasks||[]).slice(0,3)}catch(e){}if(!a.length)a=[{description:'Medicinali',dateText:'Oggi · 09:00'},{description:'Visita medica',dateText:'Lun · 16:00'},{description:'Documento',dateText:'12 Apr · 10:00'}];const d=document.createElement('div');d.className='todoRecentSection';d.innerHTML='<div class="todoRecentTitle">PROMEMORIA RECENTI</div>'+a.map((t,i)=>'<div class="todoRecentRow"><span class="todoRecentIcon">'+(i===0?'●':i===1?'▣':'◇')+'</span><span><strong>'+(t.description||t.name||'Attività')+'</strong><small>'+(t.dateText||t.date||'Promemoria')+'</small></span><span class="todoRecentArrow">›</span></div>').join('');b.insertBefore(d,b.querySelector('.modalBtns')||null)}};
const theme=()=>{const m=$('modal');if(m&&m.querySelector('[data-ttheme]'))m.classList.add('todoSettingsModal','todoThemeModal')};const color=()=>{const m=$('modal');if(m&&m.querySelector('[data-tcolor]'))m.classList.add('todoSettingsModal','todoColorModal')};
const backup=()=>{const m=$('modal'),b=$('modalBody'),menu=b?.querySelector('.settingsSubMenu');if(!m||!menu||!$('backupAuto'))return;m.classList.add('todoSettingsModal','todoBackupModal');if($('modalTitle'))$('modalTitle').textContent='Backup';hero('I tuoi dati al sicuro','Esegui il backup dei tuoi dati e ripristinali quando vuoi.');if(!b.querySelector('.todoLastBackupRow')){const x=document.createElement('div');x.className='todoLastBackupRow';x.innerHTML='<span class="ico">▣</span><span><strong>Ultimo backup</strong><small>Data e ora dell’ultimo salvataggio</small></span><time>Non ancora</time>';menu.insertBefore(x,$('backupRestore')||null)}const auto=$('backupAuto')?.closest('.settingsSubRow');[auto,$('backupExport'),$('backupImport'),b.querySelector('.todoLastBackupRow'),$('backupRestore')].forEach(x=>x&&menu.appendChild(x));if(!b.querySelector('.todoBackupExtras')){const x=document.createElement('div');x.className='todoBackupExtras';x.innerHTML='<div class="todoBackupExtrasTitle">Strumenti aggiuntivi</div>';[$('backupCreate'),$('backupLocal'),$('backupDeleteAll')].forEach(n=>n&&x.appendChild(n));b.appendChild(x)}};
const privacy=()=>{const m=$('modal'),b=$('modalBody'),menu=b?.querySelector('.settingsSubMenu');if(!m||!menu||!$('securityPinToggle'))return;m.classList.add('todoSettingsModal','todoPrivacyModal');if($('modalTitle'))$('modalTitle').textContent='Privacy';const p=$('securityPinToggle')?.closest('.settingsSubRow');if(p&&p.querySelector('strong'))p.querySelector('strong').textContent='PIN di accesso';const d=$('securityDeviceToggle')?.closest('.settingsSubRow');if(d){if(d.querySelector('strong'))d.querySelector('strong').textContent='Sblocco biometrico';if(d.querySelector('small'))d.querySelector('small').textContent='Usa impronta digitale o riconoscimento del volto'}if(!menu.querySelector('.todoPrivacyInfoRow')){const x=document.createElement('div');x.className='todoPrivacyInfoRow';x.innerHTML='<span class="ico">▣</span><span><strong>I tuoi dati restano sul dispositivo</strong><small>Le tue attività e impostazioni non vengono condivise.</small></span><span>›</span>';menu.appendChild(x)}};
const wire=()=>{if(document.documentElement.dataset.todoDecorators)return;document.documentElement.dataset.todoDecorators='1';document.addEventListener('click',e=>{const t=e.target.closest?.('button');if(!t)return;const later=f=>setTimeout(f,0);if(t.id==='todoSettingNotifications')later(notifications);else if(t.id==='todoSettingTheme')later(theme);else if(t.id==='todoSettingColor')later(color);else if(t.id==='todoSettingBackup')later(backup);else if(t.id==='todoSettingPrivacy')later(privacy);else if(['todoHubSettings','todoActiveSettings','todoDoneSettings'].includes(t.id))later(settings)},true);const s=$('todoSettings');if(s)new MutationObserver(settings).observe(s,{attributes:true,attributeFilter:['class']});settings()};
const install=()=>{if(!document.getElementById('todoLockedStylePatch')){const s=document.createElement('style');s.id='todoLockedStylePatch';s.textContent=css;document.head.appendChild(s)}wire()};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
