window.InOrdineNative=window.InOrdineNative||null;
(function(){
const css=`
/* 04/10/2026 — stile Todo definitivo, leggero e semanticamente multicolore. */
#todoHub .todoHubCard.pending,#todoHub .todoHubCard.completed{min-height:220px!important;padding:16px!important;border:1px solid #c8e9d8!important;background:radial-gradient(circle at 23% 22%,rgba(61,203,147,.10) 0 34px,transparent 35px),radial-gradient(circle at 78% 42%,rgba(61,203,147,.08) 0 18px,transparent 19px),linear-gradient(155deg,#fff 0 58%,#f1fbf6 59% 100%)!important;overflow:hidden!important}
#todoHub .todoHubCard.pending:after,#todoHub .todoHubCard.completed:after{content:"";position:absolute;left:-12%;right:-12%;bottom:28px;height:62px;pointer-events:none;background:linear-gradient(168deg,transparent 0 24%,rgba(45,190,137,.08) 25% 35%,transparent 36% 51%,rgba(45,190,137,.06) 52% 61%,transparent 62%)}
#todoHub .todoHubCard.pending>span:first-child,#todoHub .todoHubCard.completed>span:first-child{padding-top:92px!important;position:relative;z-index:2}
#todoHub .todoHubPerson{top:15px!important;right:15px!important;width:46px!important;height:46px!important;z-index:3}#todoHub .todoHubPerson img{width:46px!important;height:46px!important;border-radius:10px!important}
#todoHub .todoHubCard.pending .chev{background:#fff2d9!important;color:#c98016!important;border:1px solid #f1d7a7!important}#todoHub .todoHubCard.completed .chev{background:#e2f5e9!important;color:#148050!important;border:1px solid #c9e9d7!important}
#todoHub .todoHubCard.notify .icon,#todoHub .todoHubCard.notify .chev{background:#e7f4ff!important;color:#167fc5!important}#todoHub .todoHubCard.config .icon,#todoHub .todoHubCard.config .chev{background:#f0ebff!important;color:#7657c4!important}#todoHub .todoHubCard.reopen .icon,#todoHub .todoHubCard.reopen .chev{background:#e6f7f3!important;color:#138b78!important}
#todoHub .todoHubCard.notify,#todoHub .todoHubCard.config,#todoHub .todoHubCard.reopen{border-color:#e0ece6!important;background:#fff!important}
#todoActive .todoHero,#todoDone .todoHero{background:#fff!important;border-color:#d8ebe1!important}#todoActive .todoFilterAll.active,#todoDone .todoFilterAll.active{background:#178f63!important;border-color:#178f63!important}
#todoActive .todoTaskRow,#todoDone .todoDoneRow{background:#fff!important;border-color:#e3ece7!important}#todoActive .todoTaskRow{min-height:58px!important;padding:6px 9px!important;margin-bottom:6px!important}#todoDone .todoDoneRow{min-height:54px!important;padding:5px 8px!important;margin-bottom:6px!important}#todoActive .todoNotifyBtn,#todoActive .todoNotifyToggle{background:#e7f4ff!important;color:#157fc5!important;border:1px solid #d1e8f7!important}#todoActive .todoNotifyBtn.on,#todoActive .todoNotifyToggle.on{background:#e1f5e8!important;color:#148652!important;border-color:#c8e9d4!important}
#todoActive .todoCompleteBtn{min-height:38px!important;background:#108954!important;color:#fff!important;border:0!important;border-radius:999px!important;box-shadow:none!important;font-size:10px!important;font-weight:850!important}#todoActive .todoCompleteCircle{display:none!important}#todoActive .todoTaskEditCard.overdue{border-left:4px solid #d84b56!important}#todoActive .todoTaskEditCard.overdue small{color:#c13d47!important}
#todoDone .todoDoneStatus{background:#e2f4e8!important;color:#177b4b!important;border:1px solid #cfe8d8!important}#todoDone .todoDoneRow:nth-child(4n+1){border-left:4px solid #4a90d9!important}#todoDone .todoDoneRow:nth-child(4n+2){border-left:4px solid #7a5ac8!important}#todoDone .todoDoneRow:nth-child(4n+3){border-left:4px solid #e09b26!important}#todoDone .todoDoneRow:nth-child(4n+4){border-left:4px solid #1a9a78!important}
/* 20 Impostazioni */
#todoSettings .todoHero.settings{min-height:94px!important;padding:18px 16px 16px 82px!important;background:linear-gradient(135deg,#fff,var(--todoBg,#f1fbf6))!important;border:1px solid #bfe6d1!important;box-shadow:0 5px 15px rgba(25,103,69,.05)!important}#todoSettings .todoHero.settings .todoHeroArt{left:16px!important;right:auto!important;top:19px!important;width:52px!important;height:52px!important}#todoSettings .todoHero.settings .todoHeroArt img{width:52px!important;height:52px!important;border-radius:12px!important}#todoSettings .todoHero.settings strong{font-size:17px!important;color:#153729!important}#todoSettings .todoHero.settings small{font-size:11px!important;line-height:1.35!important;color:#6f8177!important}
#todoSettings .todoSettingsStack{gap:8px!important;margin-top:11px!important}#todoSettings .todoSettingCard{min-height:63px!important;padding:9px 12px!important;border-color:#dcebe3!important;background:var(--todoSurface,#fff)!important;box-shadow:0 3px 10px rgba(32,83,59,.035)!important}#todoSettings .todoSettingCard .i{width:36px!important;height:36px!important;display:grid!important;place-items:center!important}
#todoSettings .todoSettingCard:nth-of-type(1) .i{background:#f0ebff!important;color:#7657c4!important}#todoSettings .todoSettingCard:nth-of-type(2) .i{background:#e5f7f2!important;color:#148d78!important}#todoSettings .todoSettingCard:nth-of-type(3) .i{background:#e7f4ff!important;color:#167fc5!important}#todoSettings .todoSettingCard:nth-of-type(4) .i{background:#fff0dc!important;color:#cc7d13!important}#todoSettings .todoSettingCard:nth-of-type(5) .i{background:#eee9ff!important;color:#694eb4!important}#todoSettings .todoSettingCard:nth-of-type(6) .i{background:#e7f4ff!important;color:#167fc5!important}
/* Modali Todo 19-24 */
.modal.todoSettingsModal{background:rgba(7,35,25,.24)!important}.modal.todoSettingsModal .modalCard{background:linear-gradient(165deg,transparent 0 82%,rgba(66,199,146,.07) 83% 88%,transparent 89%),linear-gradient(180deg,#fcfffd,#f4fbf7)!important;border:1px solid #d6ebe0!important;box-shadow:0 18px 44px rgba(18,75,49,.14)!important}.modal.todoSettingsModal .modalHead{border-bottom:1px solid #e2eee7!important;padding-bottom:10px!important}.modal.todoSettingsModal .modalTitle{color:#163b2d!important;font-size:24px!important}.modal.todoSettingsModal .close{background:#e9f6ef!important;color:#167453!important}
.modal.todoSettingsModal .todoThemeIntro{min-height:104px!important;border:1px solid #bfe7d1!important;background:linear-gradient(135deg,#fff,#f0fbf5)!important;box-shadow:0 4px 12px rgba(25,103,69,.045)!important}.modal.todoSettingsModal .todoThemeIntro img{width:52px!important;height:52px!important;border-radius:12px!important}.modal.todoSettingsModal .modalBtns{position:sticky!important;bottom:0!important;padding:10px 0 2px!important;background:linear-gradient(180deg,rgba(244,251,247,0),#f4fbf7 28%)!important;gap:9px!important}.modal.todoSettingsModal .modalBtns .btn{background:#168c60!important;color:#fff!important;box-shadow:none!important}.modal.todoSettingsModal .modalBtns .btn.secondary{background:#fff!important;color:#486458!important;border:1px solid #d6e6dd!important}
/* 19 Notifiche */
.modal.todoNotificationsModal .settingsSubRow{background:#fff!important;border:1px solid #dceae3!important;border-radius:14px!important;margin:7px 0!important}.modal.todoNotificationsModal .settingsSubRow .settingsRowIcon{background:#e7f4ff!important;color:#167fc5!important}.modal.todoNotificationsModal .card{background:#fff!important;border:1px solid #dceae3!important;border-radius:16px!important;box-shadow:none!important}.modal.todoNotificationsModal .settingsTitle{font-size:12px!important;letter-spacing:.5px!important;text-transform:uppercase!important;color:#598071!important}.modal.todoNotificationsModal .field{margin:10px 0!important}.modal.todoNotificationsModal .field label{color:#315648!important;font-size:11px!important}.modal.todoNotificationsModal select,.modal.todoNotificationsModal input[type="time"],.modal.todoNotificationsModal input[type="number"]{border-color:#d9e8e0!important;background:#fbfdfc!important}
.todoRecentSection{margin:11px 0 2px}.todoRecentTitle{font-size:11px;font-weight:900;color:#5d796d;letter-spacing:.5px;margin:0 4px 6px}.todoRecentRow{display:grid;grid-template-columns:32px minmax(0,1fr) 18px;gap:8px;align-items:center;min-height:47px;padding:7px 9px;border-bottom:1px solid #e7efea;background:#fff}.todoRecentRow:first-of-type{border-radius:13px 13px 0 0}.todoRecentRow:last-child{border-radius:0 0 13px 13px;border-bottom:0}.todoRecentIcon{width:30px;height:30px;border-radius:50%;display:grid;place-items:center;background:#e8f4ff;color:#167fc5;font-size:15px}.todoRecentRow:nth-child(3) .todoRecentIcon{background:#f0ebff;color:#7456bd}.todoRecentRow:nth-child(4) .todoRecentIcon{background:#fff0dc;color:#c98217}.todoRecentRow strong{display:block;font-size:11px;color:#203e32}.todoRecentRow small{display:block;font-size:9px;color:#7b8d84;margin-top:2px}.todoRecentArrow{color:#86a296}
/* 21 Tema */
.modal.todoThemeModal .todoThemeOption{grid-template-columns:76px minmax(0,1fr) 26px!important;min-height:96px!important;padding:9px 10px!important;background:#fff!important;border-color:#dceae3!important}.modal.todoThemeModal .todoThemeOption.active{background:#f5fcf8!important;border-color:#6ac79d!important}.modal.todoThemeModal .todoThemeIcon{width:68px!important;height:62px!important;border-radius:10px!important;font-size:0!important;border:1px solid #d7e7df!important;box-shadow:none!important;position:relative!important;overflow:hidden!important}.modal.todoThemeModal .todoThemeOption:nth-child(1) .todoThemeIcon{background:linear-gradient(180deg,#f9fffb 0 16%,#dff4e8 17% 22%,#fff 23% 100%)!important}.modal.todoThemeModal .todoThemeOption:nth-child(2) .todoThemeIcon{background:linear-gradient(180deg,#13231b 0 16%,#294a38 17% 22%,#1d3026 23% 100%)!important}.modal.todoThemeModal .todoThemeOption:nth-child(3) .todoThemeIcon{background:linear-gradient(90deg,#f8fdf9 0 50%,#1d3026 50% 100%)!important}.modal.todoThemeModal .todoThemeIcon:after{content:"";position:absolute;left:9px;right:9px;top:22px;height:6px;border-radius:4px;background:currentColor;opacity:.18;box-shadow:0 11px 0 currentColor,0 22px 0 currentColor}
/* 22 Colore */
.modal.todoColorModal .todoColorChoice{min-height:68px!important;border-color:#dceae3!important;background:#fff!important}.modal.todoColorModal .todoColorChoice.active{background:#f5fcf8!important;border-color:#6ac79d!important}.modal.todoColorModal .todoColorPreview{border-color:#dceae3!important;background:#fff!important}
/* 23 Backup */
.modal.todoBackupModal .settingsSubMenu,.modal.todoPrivacyModal .settingsSubMenu{display:flex!important;flex-direction:column!important;gap:7px!important}.modal.todoBackupModal .settingsSubRow,.modal.todoPrivacyModal .settingsSubRow{margin:0!important;background:#fff!important;border:1px solid #dceae3!important;border-radius:14px!important;min-height:70px!important}.modal.todoBackupModal .settingsRowIcon.iPurple{background:#efeaff!important;color:#7358bd!important}.modal.todoBackupModal .settingsRowIcon.iBlue,.modal.todoPrivacyModal .settingsRowIcon.iBlue{background:#e7f4ff!important;color:#167fc5!important}.modal.todoBackupModal .settingsRowIcon.iGreen,.modal.todoPrivacyModal .settingsRowIcon.iGreen{background:#e2f5e9!important;color:#168151!important}.modal.todoBackupModal .settingsRowIcon.iOrange,.modal.todoPrivacyModal .settingsRowIcon.iOrange{background:#fff0dc!important;color:#c98217!important}.modal.todoBackupModal .settingsRowIcon.iRed{background:#ffe8e9!important;color:#c73b46!important}
.todoLastBackupRow,.todoPrivacyInfoRow{display:grid;grid-template-columns:38px minmax(0,1fr) auto;gap:10px;align-items:center;min-height:58px;padding:9px 11px;background:#fff;border:1px solid #dceae3;border-radius:14px}.todoLastBackupRow .ico,.todoPrivacyInfoRow .ico{width:34px;height:34px;border-radius:50%;display:grid;place-items:center;background:#e7f4ff;color:#167fc5;font-weight:900}.todoLastBackupRow strong,.todoPrivacyInfoRow strong{display:block;font-size:12px;color:#203f32}.todoLastBackupRow small,.todoPrivacyInfoRow small{display:block;font-size:9px;color:#7b8d84;margin-top:2px}.todoLastBackupRow time{font-size:9px;color:#568272;font-weight:800}.todoBackupExtras{margin-top:190px;padding-top:6px;border-top:1px dashed #d7e7df}.todoBackupExtras>summary{padding:7px 3px;color:#6f8378;font-size:10px;font-weight:850;cursor:pointer;list-style:none}.todoBackupExtras>summary::-webkit-details-marker{display:none}.todoBackupExtras[open]>.settingsSubMenu{display:flex;flex-direction:column;gap:7px}.todoPrivacyDeleteRow .settingsRowIcon{background:#ffe8e9!important;color:#c73b46!important}.todoPrivacyDeleteRow strong{color:#b7333e!important}
.modal.todoSettingsModal .settingToggle{appearance:none!important;-webkit-appearance:none!important;position:relative!important;flex:none!important;width:48px!important;height:28px!important;min-height:28px!important;padding:0!important;border:0!important;border-radius:999px!important;background:#d6e3dc!important;box-shadow:none!important;cursor:pointer!important}
.modal.todoSettingsModal .settingToggle:before{content:"";position:absolute;left:3px;top:3px;width:22px;height:22px;border-radius:50%;background:#fff;box-shadow:0 1px 3px rgba(0,0,0,.18);transition:transform .15s ease}
.modal.todoSettingsModal .settingToggle:checked{background:#15935e!important}
.modal.todoSettingsModal .settingToggle:checked:before{transform:translateX(20px)}
.modal.todoNotificationsModal .todoNotifyMasterRow input[type=checkbox]{appearance:none!important;-webkit-appearance:none!important;position:relative!important;flex:none!important;width:48px!important;height:28px!important;min-height:28px!important;padding:0!important;border:0!important;border-radius:999px!important;background:#d6e3dc!important;accent-color:transparent!important;cursor:pointer!important}
.modal.todoNotificationsModal .todoNotifyMasterRow input[type=checkbox]:before{content:"";position:absolute;left:3px;top:3px;width:22px;height:22px;border-radius:50%;background:#fff;box-shadow:0 1px 3px rgba(0,0,0,.18);transition:transform .15s ease}
.modal.todoNotificationsModal .todoNotifyMasterRow input[type=checkbox]:checked{background:#15935e!important}
.modal.todoNotificationsModal .todoNotifyMasterRow input[type=checkbox]:checked:before{transform:translateX(20px)}
#todoSetup .todoNotifyToggle{position:relative!important;width:44px!important;height:25px!important;margin:5px auto 0!important;border:0!important;border-radius:999px!important;background:#d6e3dc!important;color:transparent!important;box-shadow:none!important}
#todoSetup .todoNotifyToggle .todoLineBell{width:18px!important;height:18px!important;opacity:0!important}
#todoSetup .todoNotifyToggle:before{content:"";position:absolute;left:3px;top:3px;width:19px;height:19px;border-radius:50%;background:#fff;box-shadow:0 1px 3px rgba(0,0,0,.18);transition:transform .15s ease}
#todoSetup .todoNotifyToggle.on{background:#15935e!important}
#todoSetup .todoNotifyToggle.on:before{transform:translateX(19px)}
`;
const $=id=>document.getElementById(id);
const hero=(title,copy)=>{const b=$('modalBody');if(!b||b.querySelector('.todoMasterHero'))return;const h=document.createElement('div');h.className='todoThemeIntro todoColorIntro todoMasterHero';h.innerHTML='<img src="assets/eds-green-approved.png" alt=""><div><strong>'+title+'</strong><small>'+copy+'</small></div>';b.prepend(h)};
const settings=()=>{const s=$('todoSettings');if(!s||s.classList.contains('hidden'))return;const t=$('todoSettingsGreeting');if(t)t.textContent='Personalizza la tua esperienza';const x=s.querySelector('.todoHero.settings small');if(x)x.textContent='Gestisci le impostazioni della sezione Cose da fare.'};
const notifications=()=>{const m=$('modal'),b=$('modalBody'),n=$('todoGlobalNotify');if(!m||!b||!n)return;m.classList.add('todoSettingsModal','todoNotificationsModal');const r=n.closest('.settingsSubRow');if(r){const a=r.querySelector('strong'),c=r.querySelector('small'),i=r.querySelector('.settingsRowIcon');if(a)a.textContent='Notifiche attive';if(c)c.textContent='Ricevi promemoria per le tue attività';if(i)i.textContent='🔔'}const card=b.querySelector('.card');if(card){const st=card.querySelector('.settingsTitle');if(st)st.textContent='Promemoria';const f=$('todoGlobalRuleTiming')?.closest('.field');if(f&&f.querySelector('label'))f.querySelector('label').textContent='Anticipo promemoria'}if(!b.querySelector('.todoRecentSection')){let a=[];try{const s=JSON.parse(localStorage.getItem('inOrdineContiV1')||'{}');a=(s.todo?.tasks||[]).slice(0,3)}catch(e){}if(!a.length)a=[{description:'Medicinali',dateText:'Oggi · 09:00'},{description:'Visita medica',dateText:'Lun · 16:00'},{description:'Documento',dateText:'12 Apr · 10:00'}];const d=document.createElement('div');d.className='todoRecentSection';d.innerHTML='<div class="todoRecentTitle">PROMEMORIA RECENTI</div>'+a.map((t,i)=>'<div class="todoRecentRow"><span class="todoRecentIcon">'+(i===0?'●':i===1?'▣':'◇')+'</span><span><strong>'+(t.description||t.name||'Attività')+'</strong><small>'+(t.dateText||t.date||'Promemoria')+'</small></span><span class="todoRecentArrow">›</span></div>').join('');b.insertBefore(d,b.querySelector('.modalBtns')||null)}};
const theme=()=>{const m=$('modal');if(m&&m.querySelector('[data-ttheme]'))m.classList.add('todoSettingsModal','todoThemeModal')};const color=()=>{const m=$('modal');if(m&&m.querySelector('[data-tcolor]'))m.classList.add('todoSettingsModal','todoColorModal')};
const backup=()=>{const m=$('modal'),b=$('modalBody'),menu=b?.querySelector('.settingsSubMenu');if(!m||!menu||!$('backupAuto'))return;m.classList.add('todoSettingsModal','todoBackupModal');if($('modalTitle'))$('modalTitle').textContent='Backup';if(!b.querySelector('.todoBackupIntro'))hero('I tuoi dati al sicuro','Esegui il backup dei tuoi dati e ripristinali quando vuoi.');const auto=$('backupAuto')?.closest('.settingsSubRow'),last=menu.querySelector('.backupLastRow'),extras=menu.querySelector('#backupExtras');[auto,$('backupExport'),$('backupImport'),last,$('backupRestore')].forEach(x=>x&&menu.appendChild(x));if(extras){const tools=[...extras.querySelectorAll('#backupCreate,#backupLocal,#backupDeleteAll')];extras.remove();const disclosure=document.createElement('details');disclosure.id='backupExtras';disclosure.className='todoBackupExtras';disclosure.innerHTML='<summary>Strumenti aggiuntivi</summary><div class="settingsSubMenu"></div>';const body=disclosure.querySelector('.settingsSubMenu');tools.forEach(n=>body.appendChild(n));b.appendChild(disclosure)}};
const privacy=()=>{const m=$('modal'),b=$('modalBody'),menu=b?.querySelector('.settingsSubMenu');if(!m||!menu||!$('securityPinToggle'))return;m.classList.add('todoSettingsModal','todoPrivacyModal');if($('modalTitle'))$('modalTitle').textContent='Privacy';const p=$('securityPinToggle')?.closest('.settingsSubRow');if(p&&p.querySelector('strong'))p.querySelector('strong').textContent='PIN di accesso';const d=$('securityDeviceToggle')?.closest('.settingsSubRow');if(d){if(d.querySelector('strong'))d.querySelector('strong').textContent='Sblocco biometrico';if(d.querySelector('small'))d.querySelector('small').textContent='Usa impronta digitale o riconoscimento del volto'}if(!menu.querySelector('.todoPrivacyInfoRow')){const x=document.createElement('div');x.className='todoPrivacyInfoRow';x.innerHTML='<span class="ico">▣</span><span><strong>I tuoi dati restano sul dispositivo</strong><small>Le tue attività e impostazioni non vengono condivise.</small></span><span>›</span>';menu.appendChild(x)}if(!menu.querySelector('#todoPrivacyDeleteData')){const x=document.createElement('button');x.id='todoPrivacyDeleteData';x.className='settingsSubRow todoPrivacyDeleteRow';x.innerHTML='<span class="settingsRowIcon">×</span><span><strong>Cancella dati app</strong><small>Elimina dati e attività salvati sul dispositivo.</small></span><span class="settingsRowArrow">›</span>';x.onclick=()=>{$('todoSettingBackup')?.click();setTimeout(()=>$('backupDeleteAll')?.click(),0)};menu.appendChild(x)}};
const wire=()=>{if(document.documentElement.dataset.todoDecorators)return;document.documentElement.dataset.todoDecorators='1';document.addEventListener('click',e=>{const t=e.target.closest?.('button');if(!t)return;const later=f=>setTimeout(f,0);if(t.id==='todoSettingNotifications')later(notifications);else if(t.id==='todoSettingTheme')later(theme);else if(t.id==='todoSettingColor')later(color);else if(t.id==='todoSettingBackup')later(backup);else if(t.id==='todoSettingPrivacy')later(privacy);else if(['todoHubSettings','todoActiveSettings','todoDoneSettings'].includes(t.id))later(settings)},true);const s=$('todoSettings');if(s)new MutationObserver(settings).observe(s,{attributes:true,attributeFilter:['class']});settings()};
const install=()=>{if(!document.getElementById('todoLockedStylePatch')){const s=document.createElement('style');s.id='todoLockedStylePatch';s.textContent=css+`
/* Targeted runtime alignment: screen 17 only */
#todoActive .todoTaskRow{display:grid!important;grid-template-columns:56px minmax(0,1fr) 105px!important;column-gap:10px!important;align-items:center!important;min-height:78px!important;padding:8px 10px!important;margin-bottom:8px!important;border-radius:16px!important;background:linear-gradient(135deg,#f8fff9,#eafff3)!important}
#todoActive .todoNotifyBtn{grid-column:1!important;grid-row:1!important;justify-self:center!important;width:44px!important;height:44px!important;margin:0!important;background:#dff8ec!important;color:#0a9866!important;border:0!important}
#todoActive .todoNotifyBtn .todoLineBell{width:28px!important;height:28px!important}
#todoActive .todoTaskEditCard{grid-column:2!important;grid-row:1!important;display:block!important;min-width:0!important;width:100%!important;min-height:0!important;padding:0!important;margin:0!important;text-align:left!important;background:transparent!important;border:0!important;border-radius:0!important}
#todoActive .todoTaskEditCard:before{display:none!important;content:none!important}
#todoActive .todoTaskEditCard strong{display:block!important;font-size:14px!important;line-height:1.16!important;white-space:normal!important;word-break:normal!important;overflow-wrap:normal!important;color:#102c21!important}
#todoActive .todoTaskEditCard small{display:block!important;margin-top:5px!important;font-size:11.5px!important;line-height:1.18!important;white-space:normal!important;word-break:normal!important;overflow-wrap:normal!important;color:#13885a!important}
#todoActive .todoCompleteBtn{grid-column:3!important;grid-row:1!important;width:100%!important;min-width:0!important;min-height:42px!important;height:42px!important;padding:0 8px!important;border-radius:999px!important;display:flex!important;align-items:center!important;justify-content:center!important;background:#108954!important;color:#fff!important}
#todoActive .todoCompleteBtn span:first-child{font-size:0!important;line-height:1!important;white-space:nowrap!important}
#todoActive .todoCompleteBtn span:first-child:before{content:"✓  Segna come fatta";font-size:10px!important;font-weight:850!important;white-space:nowrap!important}
#todoActive .todoCompleteCircle{display:none!important}
`;document.head.appendChild(s)}wire()};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();

(function(){
const KEY='inOrdineContiV1';
const q=id=>document.getElementById(id);
const style=document.createElement('style');style.id='todoQuickFilterStyle';style.textContent=`
#todoActive .todoFilterBar,#todoDone .todoFilterBar{display:flex!important;grid-template-columns:none!important;gap:7px!important;align-items:center!important}
.todoQuickFilter{flex:1;min-height:38px;border:1px solid #cfe6da;border-radius:999px;background:#fff;color:#3f5e50;font-size:10.5px;font-weight:850;padding:7px 8px;white-space:nowrap}
.todoQuickFilter.active{background:#168d61;color:#fff;border-color:#168d61}
.todoAdvancedFilters{margin:2px 0 8px;border:0;background:transparent}.todoAdvancedFilters summary{list-style:none;text-align:right;color:#6d8177;font-size:10px;font-weight:800;cursor:pointer;padding:2px 5px}.todoAdvancedFilters summary::-webkit-details-marker{display:none}.todoAdvancedFilters summary:before{content:'＋ ';color:#168d61}.todoAdvancedFilters[open] summary:before{content:'− '}.todoAdvancedFilterInner{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:6px}.todoAdvancedFilterInner .todoFilterSelect{width:100%!important}
#todoSetup:not(.hidden){scroll-margin-top:0}
`;
document.head.appendChild(style);
const localDateISO=d=>{const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return y+'-'+m+'-'+day};
const monday=d=>{const x=new Date(d.getFullYear(),d.getMonth(),d.getDate()),n=(x.getDay()+6)%7;x.setDate(x.getDate()-n);return x};
const within=(iso,a,b)=>!!iso&&iso>=localDateISO(a)&&iso<=localDateISO(b);
function data(kind){try{const s=JSON.parse(localStorage.getItem(KEY)||'{}');return kind==='active'?(s.todo?.tasks||[]):(s.todo?.done||[])}catch(e){return[]}}
function rowName(row){return (row.querySelector('strong')?.textContent||'').trim()}
function matchItem(kind,name){return data(kind).find(x=>(x.description||'').trim()===name)}
function apply(kind,mode){const list=q(kind==='active'?'todoActiveList':'todoDoneList');if(!list)return;const now=new Date(),start=monday(now),end=new Date(start);end.setDate(end.getDate()+6);const monthStart=new Date(now.getFullYear(),now.getMonth(),1),monthEnd=new Date(now.getFullYear(),now.getMonth()+1,0);[...list.children].forEach(row=>{if(!row.classList.contains(kind==='active'?'todoTaskRow':'todoDoneRow'))return;const item=matchItem(kind,rowName(row));const iso=kind==='active'?item?.date:item?.completedAt;let show=true;if(mode==='today')show=iso===localDateISO(now);else if(mode==='week')show=within(iso,start,end);else if(mode==='month')show=within(iso,monthStart,monthEnd);row.style.display=show?'':'none'});const root=q(kind==='active'?'todoActive':'todoDone');root?.querySelectorAll('.todoQuickFilter').forEach(b=>b.classList.toggle('active',b.dataset.quick===mode))}
function resetAdvanced(kind){const prefix=kind==='active'?'todoActive':'todoDone',m=q(prefix+'FilterMonth'),y=q(prefix+'FilterYear');if(m&&m.value!=='all'){m.value='all';m.dispatchEvent(new Event('change',{bubbles:true}))}if(y&&y.value!=='all'){y.value='all';y.dispatchEvent(new Event('change',{bubbles:true}))}}
function decorate(kind){const prefix=kind==='active'?'todoActive':'todoDone',root=q(prefix.replace('Filter','')),bar=root?.querySelector('.todoFilterBar'),all=q(prefix+'FilterAll'),m=q(prefix+'FilterMonth'),y=q(prefix+'FilterYear');if(!root||!bar||!all||!m||!y||bar.dataset.quickReady)return;bar.dataset.quickReady='1';all.classList.add('todoQuickFilter');all.dataset.quick='all';all.textContent='Tutte';const labels=kind==='active'?[['today','Oggi'],['week','Questa settimana']]:[['today','Oggi'],['week','Questa settimana'],['month','Questo mese']];labels.forEach(([mode,label])=>{const b=document.createElement('button');b.className='todoQuickFilter';b.dataset.quick=mode;b.textContent=label;b.type='button';b.addEventListener('click',()=>{resetAdvanced(kind);setTimeout(()=>apply(kind,mode),0)});bar.appendChild(b)});all.addEventListener('click',()=>setTimeout(()=>apply(kind,'all'),0));const details=document.createElement('details');details.className='todoAdvancedFilters';details.innerHTML='<summary>Filtri mese e anno</summary><div class="todoAdvancedFilterInner"></div>';const inner=details.querySelector('div');inner.append(m,y);bar.after(details);const list=q(kind==='active'?'todoActiveList':'todoDoneList');if(list)new MutationObserver(()=>{const current=root.querySelector('.todoQuickFilter.active')?.dataset.quick||'all';apply(kind,current)}).observe(list,{childList:true});apply(kind,'all')}
function onScreen(){['active','done'].forEach(decorate);const setup=q('todoSetup');if(setup&&!setup.classList.contains('hidden')){window.scrollTo(0,0);document.documentElement.scrollTop=0;document.body.scrollTop=0}}
function start(){onScreen();['todoSetup','todoActive','todoDone'].forEach(id=>{const el=q(id);if(el)new MutationObserver(onScreen).observe(el,{attributes:true,attributeFilter:['class']})})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
