import {loadState,saveState} from './state.js';
const app=document.querySelector('#app'); let state=await loadState();
const euro=n=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(n)||0);
const realBalance=()=>Number(state.balance)||0;
function shell(body){app.innerHTML='<main class="app-shell"><section class="screen"><div class="screen-inner">'+body+'</div></section></main>'}
function landing(){shell('<div class="brand card"><strong>In Ordine</strong><span>E.D.S.</span><p>Conti e cose da fare, in un unico posto.</p></div><div class="area-grid"><button class="area-card money" data-go="money"><b>Conti economici</b><small>Saldo, entrate, pagamenti e movimenti</small></button><button class="area-card todo" data-go="todo"><b>Cose da fare</b><small>Attività, scadenze e promemoria</small></button></div>')}
function money(){shell('<header class="page-header money-head"><button data-go="landing">‹</button><div><small>IN ORDINE</small><h1>Conti economici</h1></div><span class="eds">E.D.S.</span></header><section class="balance card"><small>Saldo reale</small><strong>'+euro(realBalance())+'</strong><button id="setBalance">Imposta saldo</button></section><div class="area-grid"><button class="area-card income" data-go="income"><b>Entrate</b><small>Da ricevere e ricevute</small></button><button class="area-card expense" data-go="expense"><b>Pagamenti</b><small>Da pagare e pagati</small></button></div><button class="wide card" data-go="movements">Movimenti</button><button class="wide card" data-go="summary">Riepilogo e budget</button>')}
const uid=()=>crypto.randomUUID();
const monthOf=x=>(x.date||'').slice(0,7);
function flow(kind){const isIncome=kind==='income',title=isIncome?'Entrate':'Pagamenti',items=state.entries.filter(x=>x.kind===kind);const rows=items.length?items.map(x=>'<article class="card task money-row"><div><b>'+escapeHtml(x.description)+'</b><small>'+escapeHtml(x.category||'Altro')+' · '+(x.date||'Senza data')+'</small></div><div class="money-actions"><strong>'+euro(x.amount)+'</strong><button data-money-done="'+x.id+'">'+(isIncome?'Ricevuta':'Pagato')+'</button></div></article>').join(''):'<div class="card empty"><b>Nessuna voce</b><p>Aggiungi la prima '+title.toLowerCase()+'.</p></div>';shell('<header class="page-header money-head"><button data-go="money">‹</button><div><small>CONTI ECONOMICI</small><h1>'+title+'</h1></div><span class="eds">E.D.S.</span></header>'+rows+'<button class="wide card" data-add-money="'+kind+'">＋ Aggiungi '+(isIncome?'entrata':'pagamento')+'</button>')}
function moneyForm(kind){const isIncome=kind==='income';shell('<header class="page-header money-head"><button data-go="'+kind+'">‹</button><div><small>CONTI ECONOMICI</small><h1>Nuova '+(isIncome?'entrata':'spesa')+'</h1></div><span class="eds">E.D.S.</span></header><form id="moneyForm" data-kind="'+kind+'" class="card form-card"><label>Descrizione<input id="moneyDescription" required autocomplete="off"></label><label>Importo<input id="moneyAmount" inputmode="decimal" required></label><label>Data<input id="moneyDate" type="date"></label><label>Categoria<input id="moneyCategory" autocomplete="off" placeholder="Es. Stipendio"></label><label>Fornitore / provenienza<input id="moneySupplier" autocomplete="off"></label><button type="submit">Salva</button></form>')}
function movements(){const rows=[...state.history].sort((a,b)=>(b.completedAt||'').localeCompare(a.completedAt||'')).map(x=>'<article class="card task money-row"><div><b>'+escapeHtml(x.description)+'</b><small>'+(x.date||'')+' · '+escapeHtml(x.category||'Altro')+'</small></div><strong class="'+(x.kind==='income'?'plus':'minus')+'">'+(x.kind==='income'?'+':'−')+euro(x.amount)+'</strong></article>').join('');shell('<header class="page-header money-head"><button data-go="money">‹</button><div><small>CONTI ECONOMICI</small><h1>Movimenti</h1></div><span class="eds">E.D.S.</span></header>'+(rows||'<div class="card empty"><b>Nessun movimento</b><p>Qui compariranno soltanto entrate ricevute e pagamenti realmente effettuati.</p></div>'))}
function monthKey(d=new Date()){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')}
function budget(){const ym=monthKey(),plan=(state.budgetPlans||[]).find(x=>x.month===ym)||{month:ym,total:0,limits:{}};const spent=state.history.filter(x=>x.kind==='expense'&&monthOf(x)===ym).reduce((s,x)=>s+Number(x.amount||0),0);shell('<header class="page-header money-head"><button data-go="summary">‹</button><div><small>CONTI ECONOMICI</small><h1>Budget</h1></div><span class="eds">E.D.S.</span></header><section class="balance card"><small>Budget mensile</small><strong>'+euro(plan.total)+'</strong><p>Speso: '+euro(spent)+' · Disponibile: '+euro(Math.max(0,Number(plan.total)-spent))+'</p><button id="editBudget">Imposta budget</button></section>')}
function settings(){shell('<header class="page-header"><button data-go="landing">‹</button><div><small>IN ORDINE</small><h1>Impostazioni</h1></div><span class="eds">E.D.S.</span></header><div class="settings-list"><button class="wide card" data-setting="name">Profilo / Nome</button><button class="wide card" data-setting="color">Colore app</button><button class="wide card" data-setting="backup">Backup dati</button><button class="wide card" data-setting="privacy">Privacy e sicurezza</button></div>')}
function summary(){const inc=state.history.filter(x=>x.kind==='income').reduce((s,x)=>s+Number(x.amount||0),0),exp=state.history.filter(x=>x.kind==='expense').reduce((s,x)=>s+Number(x.amount||0),0);shell('<header class="page-header money-head"><button data-go="money">‹</button><div><small>CONTI ECONOMICI</small><h1>Riepilogo</h1></div><span class="eds">E.D.S.</span></header><section class="balance card"><small>Saldo reale</small><strong>'+euro(realBalance())+'</strong></section><div class="area-grid"><div class="area-card income"><b>Entrate ricevute</b><strong>'+euro(inc)+'</strong></div><div class="area-card expense"><b>Pagamenti effettuati</b><strong>'+euro(exp)+'</strong></div></div><section class="wide card"><b>Differenza movimenti</b><strong>'+euro(inc-exp)+'</strong></section>')}
function todo(){const pending=state.todo.tasks.length,done=state.todo.done.length;shell('<header class="page-header todo-head"><button data-go="landing">‹</button><div><small>IN ORDINE</small><h1>Cose da fare</h1></div><span class="eds">E.D.S.</span></header><div class="area-grid"><button class="area-card pending" data-go="todo-active"><b>In scadenza</b><strong>'+pending+'</strong></button><button class="area-card completed" data-go="todo-done"><b>Cose già fatte</b><strong>'+done+'</strong></button></div><button class="wide card" data-go="todo-add">＋ Aggiungi cosa da fare</button><button class="wide card" data-go="todo-settings">Impostazioni</button>')}
function todoAdd(){shell('<header class="page-header todo-head"><button data-go="todo">‹</button><div><small>COSE DA FARE</small><h1>Nuova attività</h1></div><span class="eds">E.D.S.</span></header><form id="todoForm" class="card form-card"><label>Cosa devi fare?<input id="todoDescription" required autocomplete="off"></label><label>Data<input id="todoDate" type="date"></label><label class="check"><input id="todoNotify" type="checkbox"> Promemoria</label><button type="submit">Salva attività</button></form>')}
function todoList(done=false){const items=done?state.todo.done:state.todo.tasks;const rows=items.length?items.map(x=>'<article class="card task"><div><b>'+escapeHtml(x.description)+'</b><small>'+(x.date||'Senza data')+'</small></div>'+(done?'<button data-restore="'+x.id+'">Ripristina</button>':'<button data-complete="'+x.id+'">✓ Fatta</button>')+'</article>').join(''):'<div class="card empty"><b>Nessuna attività</b><p>'+(done?'Le attività completate compariranno qui.':'Aggiungi la prima cosa da fare.')+'</p></div>';shell('<header class="page-header todo-head"><button data-go="todo">‹</button><div><small>COSE DA FARE</small><h1>'+(done?'Cose già fatte':'In scadenza')+'</h1></div><span class="eds">E.D.S.</span></header>'+rows+(done?'':'<button class="wide card" data-go="todo-add">＋ Aggiungi attività</button>'))}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
function placeholder(title,back){shell('<header class="page-header"><button data-go="'+back+'">‹</button><div><small>IN ORDINE</small><h1>'+title+'</h1></div><span class="eds">E.D.S.</span></header><div class="card empty"><b>'+title+'</b><p>La funzione viene ricostruita nella V2 mantenendo le regole dell’app originale.</p></div>')}
function route(name){if(name==='landing')landing();else if(name==='money')money();else if(name==='todo')todo();else if(name==='income'||name==='expense')flow(name);else if(name==='movements')movements();else if(name==='summary')summary();else if(name==='budget')budget();else if(name==='settings')settings();else if(name==='todo-add')todoAdd();else if(name==='todo-active')todoList(false);else if(name==='todo-done')todoList(true);else placeholder(({income:'Entrate',expense:'Pagamenti',movements:'Movimenti',summary:'Riepilogo e budget','todo-active':'In scadenza','todo-done':'Cose già fatte','todo-add':'Nuova attività','todo-settings':'Impostazioni'})[name]||'In Ordine',name.startsWith('todo-')?'todo':'money')}
app.addEventListener('submit',async e=>{if(e.target.id==='moneyForm'){e.preventDefault();const kind=e.target.dataset.kind,amount=Number(document.querySelector('#moneyAmount').value.replace(',','.'));if(!Number.isFinite(amount)||amount<=0)return;state.entries.push({id:uid(),kind,description:document.querySelector('#moneyDescription').value.trim(),amount,date:document.querySelector('#moneyDate').value||'',category:document.querySelector('#moneyCategory').value.trim(),supplier:document.querySelector('#moneySupplier').value.trim(),createdAt:new Date().toISOString()});state=await saveState(state);flow(kind);return}if(e.target.id!=='todoForm')return;e.preventDefault();const description=document.querySelector('#todoDescription').value.trim();if(!description)return;state.todo.tasks.push({id:crypto.randomUUID(),description,date:document.querySelector('#todoDate').value||'',notify:document.querySelector('#todoNotify').checked,createdAt:new Date().toISOString()});state=await saveState(state);todoList(false)});
app.addEventListener('click',async e=>{const addMoney=e.target.closest('[data-add-money]');if(addMoney){moneyForm(addMoney.dataset.addMoney);return}const moneyDone=e.target.closest('[data-money-done]');if(moneyDone){const i=state.entries.findIndex(x=>x.id===moneyDone.dataset.moneyDone);if(i>=0){const [x]=state.entries.splice(i,1);x.completedAt=new Date().toISOString();state.history.unshift(x);state.balance=realBalance()+(x.kind==='income'?Number(x.amount):-Number(x.amount));state=await saveState(state);flow(x.kind)}return}const complete=e.target.closest('[data-complete]');if(complete){const i=state.todo.tasks.findIndex(x=>x.id===complete.dataset.complete);if(i>=0){const [x]=state.todo.tasks.splice(i,1);x.completedAt=new Date().toISOString();state.todo.done.unshift(x);state=await saveState(state);todoList(false)}return}const restore=e.target.closest('[data-restore]');if(restore){const i=state.todo.done.findIndex(x=>x.id===restore.dataset.restore);if(i>=0){const [x]=state.todo.done.splice(i,1);delete x.completedAt;state.todo.tasks.unshift(x);state=await saveState(state);todoList(true)}return}const go=e.target.closest('[data-go]');if(go)return route(go.dataset.go);if(e.target.id==='editBudget'){const v=prompt('Budget totale del mese');if(v===null)return;const n=Number(v.replace(',','.'));if(Number.isFinite(n)&&n>=0){const ym=monthKey(),plans=state.budgetPlans||(state.budgetPlans=[]),i=plans.findIndex(x=>x.month===ym);const p={month:ym,total:n,limits:i>=0?plans[i].limits||{}:{}};if(i>=0)plans[i]=p;else plans.push(p);state=await saveState(state);budget()}return}if(e.target.id==='setBalance'){const v=prompt('Saldo reale attuale',String(realBalance()));if(v===null)return;const n=Number(v.replace(',','.'));if(Number.isFinite(n)){state.balance=n;state=await saveState(state);money()}}});
route('landing');
