import {loadState,saveState} from './state.js';
const app=document.querySelector('#app'); let state=await loadState();
const euro=n=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(n)||0);
const realBalance=()=>Number(state.balance)||0;
function shell(body){app.innerHTML='<main class="app-shell"><section class="screen"><div class="screen-inner">'+body+'</div></section></main>'}
function landing(){shell('<div class="brand card"><strong>In Ordine</strong><span>E.D.S.</span><p>Conti e cose da fare, in un unico posto.</p></div><div class="area-grid"><button class="area-card money" data-go="money"><b>Conti economici</b><small>Saldo, entrate, pagamenti e movimenti</small></button><button class="area-card todo" data-go="todo"><b>Cose da fare</b><small>Attività, scadenze e promemoria</small></button></div>')}
function money(){shell('<header class="page-header money-head"><button data-go="landing">‹</button><div><small>IN ORDINE</small><h1>Conti economici</h1></div><span class="eds">E.D.S.</span></header><section class="balance card"><small>Saldo reale</small><strong>'+euro(realBalance())+'</strong><button id="setBalance">Imposta saldo</button></section><div class="area-grid"><button class="area-card income" data-go="income"><b>Entrate</b><small>Da ricevere e ricevute</small></button><button class="area-card expense" data-go="expense"><b>Pagamenti</b><small>Da pagare e pagati</small></button></div><button class="wide card" data-go="movements">Movimenti</button><button class="wide card" data-go="summary">Riepilogo e budget</button>')}
const uid=()=>crypto.randomUUID();
const nativePlugin=name=>globalThis.Capacitor?.Plugins?.[name]||null;
async function syncTodoNotifications(){
  const plugin=nativePlugin('LocalNotifications'); if(!plugin)return;
  try{
    if(state.todo.notifications?.enabled){const p=await plugin.checkPermissions();if(p.display!=='granted')await plugin.requestPermissions()}
    const pending=await plugin.getPending();const ids=(pending.notifications||[]).map(x=>x.id);if(ids.length)await plugin.cancel({notifications:ids.map(id=>({id}))});
    if(!state.todo.notifications?.enabled)return;
    const notifications=state.todo.tasks.filter(x=>x.notify&&x.date).map((x,i)=>{const [h,m]=(state.todo.notifications.rule?.time||'09:00').split(':').map(Number),at=new Date(x.date+'T00:00:00');at.setHours(h,m,0,0);return {id:10000+i,title:'In Ordine',body:x.description,schedule:{at},extra:{taskId:x.id}}}).filter(x=>x.schedule.at>Date.now());
    if(notifications.length)await plugin.schedule({notifications});
  }catch(e){console.warn('Notification sync failed',e)}
}
const monthOf=x=>(x.date||'').slice(0,7);
function addMonths(ym,n){const [y,m]=ym.split('-').map(Number),d=new Date(y,m-1+n,1);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')}
let flowMonths={income:monthKey(),expense:monthKey()};
function flow(kind){const isIncome=kind==='income',title=isIncome?'Entrate':'Pagamenti',ym=flowMonths[kind]||monthKey(),filter=statusFilter(kind);let items=state.entries.filter(x=>x.kind===kind&&(!x.date||monthOf(x)===ym));const completed=state.history.filter(x=>x.kind===kind&&(!x.date||monthOf(x)===ym));if(filter==='done')items=[];if(filter==='all')items=[...items,...completed.map(x=>({...x,_done:true}))];if(filter==='done')items=completed.map(x=>({...x,_done:true}));const rows=items.length?items.map(x=>'<article class="card task money-row"><div><b>'+escapeHtml(x.description)+'</b><small>'+escapeHtml(x.category||'Altro')+' · '+(x.date||'Senza data')+(x._done?' · '+(isIncome?'Ricevuta':'Pagato'):'')+'</small></div><div class="money-actions"><strong>'+euro(x.amount)+'</strong>'+(x._done?'':'<button data-money-done="'+x.id+'">'+(isIncome?'Ricevuta':'Pagato')+'</button>')+'</div></article>').join(''):'<div class="card empty"><b>Nessuna voce</b><p>Aggiungi la prima '+title.toLowerCase()+'.</p></div>';shell('<header class="page-header money-head"><button data-go="money">‹</button><div><small>CONTI ECONOMICI</small><h1>'+title+'</h1></div><span class="eds">E.D.S.</span></header>'+todoFilterControls(source)+rows+'<button class="wide card" data-add-money="'+kind+'">＋ Aggiungi '+(isIncome?'entrata':'pagamento')+'</button>')}
function statusFilter(kind){return (state.preferences.moneyFilters||{})[kind]||'all'}
function moneyForm(kind){const isIncome=kind==='income';shell('<header class="page-header money-head"><button data-go="'+kind+'">‹</button><div><small>CONTI ECONOMICI</small><h1>Nuova '+(isIncome?'entrata':'spesa')+'</h1></div><span class="eds">E.D.S.</span></header><form id="moneyForm" data-kind="'+kind+'" class="card form-card"><label>Descrizione<input id="moneyDescription" required autocomplete="off"></label><label>Importo<input id="moneyAmount" inputmode="decimal" required></label><label>Data<input id="moneyDate" type="date"></label><label>Categoria<input id="moneyCategory" autocomplete="off" placeholder="Es. Stipendio"></label><label>Fornitore / provenienza<input id="moneySupplier" autocomplete="off"></label><label>Ricorrenza<select id="moneyRecurrence"><option value="none">Nessuna</option><option value="monthly">Ogni mese</option><option value="yearly">Ogni anno</option></select></label><button type="submit">Salva</button></form>')}
function movements(){const rows=[...state.history].sort((a,b)=>(b.completedAt||'').localeCompare(a.completedAt||'')).map(x=>'<article class="card task money-row"><div><b>'+escapeHtml(x.description)+'</b><small>'+(x.date||'')+' · '+escapeHtml(x.category||'Altro')+'</small></div><strong class="'+(x.kind==='income'?'plus':'minus')+'">'+(x.kind==='income'?'+':'−')+euro(x.amount)+'</strong></article>').join('');shell('<header class="page-header money-head"><button data-go="money">‹</button><div><small>CONTI ECONOMICI</small><h1>Movimenti</h1></div><span class="eds">E.D.S.</span></header>'+(rows||'<div class="card empty"><b>Nessun movimento</b><p>Qui compariranno soltanto entrate ricevute e pagamenti realmente effettuati.</p></div>'))}
function monthKey(d=new Date()){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')}
function budget(){const ym=monthKey(),plan=(state.budgetPlans||[]).find(x=>x.month===ym)||{month:ym,total:0,limits:{}};const spent=state.history.filter(x=>x.kind==='expense'&&monthOf(x)===ym).reduce((s,x)=>s+Number(x.amount||0),0);shell('<header class="page-header money-head"><button data-go="summary">‹</button><div><small>CONTI ECONOMICI</small><h1>Budget</h1></div><span class="eds">E.D.S.</span></header><section class="balance card"><small>Budget mensile</small><strong>'+euro(plan.total)+'</strong><p>Speso: '+euro(spent)+' · Disponibile: '+euro(Math.max(0,Number(plan.total)-spent))+'</p><button id="editBudget">Imposta budget</button></section>')}
function todoSettings(){const n=state.todo.notifications||{};shell('<header class="page-header todo-head"><button data-go="todo">‹</button><div><small>COSE DA FARE</small><h1>Impostazioni</h1></div><span class="eds">E.D.S.</span></header><form id="todoSettingsForm" class="card form-card"><label>Colore<select id="todoColor"><option>Verde E.D.S.</option><option>Blu</option><option>Viola</option><option>Arancio</option></select></label><label class="check"><input id="todoNotifications" type="checkbox" '+(n.enabled?'checked':'')+'> Notifiche attività</label><label>Ora predefinita<input id="todoNotifyTime" type="time" value="'+escapeHtml(n.rule?.time||'09:00')+'"></label><button type="submit">Salva impostazioni</button></form>')}
async function exportBackup(){const payload=JSON.stringify({format:'in-ordine-v2',exportedAt:new Date().toISOString(),state},null,2);const fs=nativePlugin('Filesystem'),share=nativePlugin('Share');if(fs&&share){const name='in-ordine-backup-'+new Date().toISOString().slice(0,10)+'.json';await fs.writeFile({path:name,data:btoa(unescape(encodeURIComponent(payload))),directory:'CACHE'});const uri=await fs.getUri({path:name,directory:'CACHE'});await share.share({title:'Backup In Ordine',url:uri.uri});return}const blob=new Blob([payload],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='in-ordine-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function categorySettings(){const cats=state.preferences.categories||['Stipendio','Pensione','Casa','Spesa','Auto','Salute','Tempo libero','Altro'];shell('<header class="page-header money-head"><button data-go="settings">‹</button><div><small>IMPOSTAZIONI</small><h1>Categorie</h1></div><span class="eds">E.D.S.</span></header><div id="categoryList">'+cats.map((x,i)=>'<article class="card task"><b>'+escapeHtml(x)+'</b><button data-delete-category="'+i+'">Elimina</button></article>').join('')+'</div><form id="categoryForm" class="card form-card"><label>Nuova categoria<input id="categoryName" required autocomplete="off"></label><button type="submit">Aggiungi categoria</button></form>')}
function profileSettings(){shell('<header class="page-header"><button data-go="settings">‹</button><div><small>IMPOSTAZIONI</small><h1>Profilo</h1></div><span class="eds">E.D.S.</span></header><form id="profileForm" class="card form-card"><label>Nome<input id="profileName" value="'+escapeHtml(state.profile?.fullName||'')+'" autocomplete="name"></label><label>Colore principale<select id="appColor"><option '+(state.appColor==='Blu'?'selected':'')+'>Blu</option><option '+(state.appColor==='Verde'?'selected':'')+'>Verde</option><option '+(state.appColor==='Viola'?'selected':'')+'>Viola</option></select></label><button type="submit">Salva</button></form>')}
function settings(){shell('<header class="page-header"><button data-go="landing">‹</button><div><small>IN ORDINE</small><h1>Impostazioni</h1></div><span class="eds">E.D.S.</span></header><div class="settings-list"><button class="wide card" data-go="profile">Profilo / Nome</button><button class="wide card" data-go="categories">Categorie</button><button class="wide card" data-setting="color">Colore app</button><button class="wide card" data-setting="backup">Backup dati</button><button class="wide card" data-setting="privacy">Privacy e sicurezza</button></div>')}
function summary(){const inc=state.history.filter(x=>x.kind==='income').reduce((s,x)=>s+Number(x.amount||0),0),exp=state.history.filter(x=>x.kind==='expense').reduce((s,x)=>s+Number(x.amount||0),0);shell('<header class="page-header money-head"><button data-go="money">‹</button><div><small>CONTI ECONOMICI</small><h1>Riepilogo</h1></div><span class="eds">E.D.S.</span></header><section class="balance card"><small>Saldo reale</small><strong>'+euro(realBalance())+'</strong></section><div class="area-grid"><div class="area-card income"><b>Entrate ricevute</b><strong>'+euro(inc)+'</strong></div><div class="area-card expense"><b>Pagamenti effettuati</b><strong>'+euro(exp)+'</strong></div></div><section class="wide card"><b>Differenza movimenti</b><strong>'+euro(inc-exp)+'</strong></section>')}
function todo(){const pending=state.todo.tasks.length,done=state.todo.done.length;shell('<header class="page-header todo-head"><button data-go="landing">‹</button><div><small>IN ORDINE</small><h1>Cose da fare</h1></div><span class="eds">E.D.S.</span></header><div class="area-grid"><button class="area-card pending" data-go="todo-active"><b>In scadenza</b><strong>'+pending+'</strong></button><button class="area-card completed" data-go="todo-done"><b>Cose già fatte</b><strong>'+done+'</strong></button></div><button class="wide card" data-go="todo-add">＋ Aggiungi cosa da fare</button><button class="wide card" data-go="todo-settings">Impostazioni</button>')}
function expandRecurring(entry){if(entry.recurrence==='none'||!entry.date)return;const count=entry.recurrence==='monthly'?11:2;for(let i=1;i<=count;i++){const d=new Date(entry.date+'T12:00:00');if(entry.recurrence==='monthly')d.setMonth(d.getMonth()+i);else d.setFullYear(d.getFullYear()+i);state.entries.push({...entry,id:uid(),date:d.toISOString().slice(0,10),recurrenceSource:entry.id})}}
let todoFilter={month:'all',year:'all'};
function todoFilterControls(items){const years=[...new Set(items.map(x=>(x.date||'').slice(0,4)).filter(Boolean))].sort();return '<div class="todo-filters"><select id="todoMonth"><option value="all">Tutti i mesi</option>'+Array.from({length:12},(_,i)=>'<option value="'+String(i+1).padStart(2,'0')+'" '+(todoFilter.month===String(i+1).padStart(2,'0')?'selected':'')+'>'+new Intl.DateTimeFormat('it-IT',{month:'long'}).format(new Date(2026,i,1))+'</option>').join('')+'</select><select id="todoYear"><option value="all">Tutti gli anni</option>'+years.map(y=>'<option '+(todoFilter.year===y?'selected':'')+'>'+y+'</option>').join('')+'</select></div>'}
function filteredTodos(items){return [...items].filter(x=>{const [y,m]=(x.date||'').split('-');return (todoFilter.month==='all'||m===todoFilter.month)&&(todoFilter.year==='all'||y===todoFilter.year)}).sort((a,b)=>{if(!a.date)return 1;if(!b.date)return -1;return a.date.localeCompare(b.date)})}
function todoAdd(){shell('<header class="page-header todo-head"><button data-go="todo">‹</button><div><small>COSE DA FARE</small><h1>Nuova attività</h1></div><span class="eds">E.D.S.</span></header><form id="todoForm" class="card form-card"><label>Cosa devi fare?<input id="todoDescription" required autocomplete="off"></label><label>Data<input id="todoDate" type="date"></label><label class="check"><input id="todoNotify" type="checkbox"> Promemoria</label><button type="submit">Salva attività</button></form>')}
function todoList(done=false){const source=done?state.todo.done:state.todo.tasks,items=filteredTodos(source);const rows=items.length?items.map(x=>'<article class="card task"><div><b>'+escapeHtml(x.description)+'</b><small>'+(x.date||'Senza data')+'</small></div>'+(done?'<button data-restore="'+x.id+'">Ripristina</button>':'<button data-complete="'+x.id+'">✓ Fatta</button>')+'</article>').join(''):'<div class="card empty"><b>Nessuna attività</b><p>'+(done?'Le attività completate compariranno qui.':'Aggiungi la prima cosa da fare.')+'</p></div>';shell('<header class="page-header todo-head"><button data-go="todo">‹</button><div><small>COSE DA FARE</small><h1>'+(done?'Cose già fatte':'In scadenza')+'</h1></div><span class="eds">E.D.S.</span></header>'+rows+(done?'':'<button class="wide card" data-go="todo-add">＋ Aggiungi attività</button>'))}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
function placeholder(title,back){shell('<header class="page-header"><button data-go="'+back+'">‹</button><div><small>IN ORDINE</small><h1>'+title+'</h1></div><span class="eds">E.D.S.</span></header><div class="card empty"><b>'+title+'</b><p>La funzione viene ricostruita nella V2 mantenendo le regole dell’app originale.</p></div>')}
function route(name){if(name==='landing')landing();else if(name==='money')money();else if(name==='todo')todo();else if(name==='income'||name==='expense')flow(name);else if(name==='movements')movements();else if(name==='summary')summary();else if(name==='budget')budget();else if(name==='categories')categorySettings();else if(name==='profile')profileSettings();else if(name==='settings')settings();else if(name==='todo-settings')todoSettings();else if(name==='todo-add')todoAdd();else if(name==='todo-active')todoList(false);else if(name==='todo-done')todoList(true);else placeholder(({income:'Entrate',expense:'Pagamenti',movements:'Movimenti',summary:'Riepilogo e budget','todo-active':'In scadenza','todo-done':'Cose già fatte','todo-add':'Nuova attività','todo-settings':'Impostazioni'})[name]||'In Ordine',name.startsWith('todo-')?'todo':'money')}
app.addEventListener('change',async e=>{if(e.target.id==='importBackup'){const file=e.target.files?.[0];if(!file)return;try{const parsed=JSON.parse(await file.text()),candidate=parsed.state||parsed;if(!candidate||typeof candidate!=='object')throw new Error();state=await saveState(candidate);await syncTodoNotifications();settings()}catch{alert('Backup non valido')}return}if(e.target.id==='todoMonth'){todoFilter.month=e.target.value;todoList(false)}if(e.target.id==='todoYear'){todoFilter.year=e.target.value;todoList(false)}});
app.addEventListener('submit',async e=>{if(e.target.id==='profileForm'){e.preventDefault();state.profile={...(state.profile||{}),fullName:document.querySelector('#profileName').value.trim()};state.appColor=document.querySelector('#appColor').value;state=await saveState(state);profileSettings();return}if(e.target.id==='categoryForm'){e.preventDefault();const name=document.querySelector('#categoryName').value.trim();if(name){const cats=state.preferences.categories||(state.preferences.categories=['Stipendio','Pensione','Casa','Spesa','Auto','Salute','Tempo libero','Altro']);if(!cats.some(x=>x.toLowerCase()===name.toLowerCase()))cats.push(name);state=await saveState(state);categorySettings()}return}if(e.target.id==='todoSettingsForm'){e.preventDefault();state.todo.color=document.querySelector('#todoColor').value;state.todo.notifications={...(state.todo.notifications||{}),enabled:document.querySelector('#todoNotifications').checked,rule:{...(state.todo.notifications?.rule||{}),time:document.querySelector('#todoNotifyTime').value||'09:00'}};state=await saveState(state);await syncTodoNotifications();todoSettings();return}if(e.target.id==='moneyForm'){e.preventDefault();const kind=e.target.dataset.kind,amount=Number(document.querySelector('#moneyAmount').value.replace(',','.'));if(!Number.isFinite(amount)||amount<=0)return;const entry={id:uid(),kind,description:document.querySelector('#moneyDescription').value.trim(),amount,date:document.querySelector('#moneyDate').value||'',category:document.querySelector('#moneyCategory').value.trim(),supplier:document.querySelector('#moneySupplier').value.trim(),recurrence:document.querySelector('#moneyRecurrence').value,createdAt:new Date().toISOString()};state.entries.push(entry);expandRecurring(entry);state=await saveState(state);flow(kind);return}if(e.target.id!=='todoForm')return;e.preventDefault();const description=document.querySelector('#todoDescription').value.trim();if(!description)return;state.todo.tasks.push({id:crypto.randomUUID(),description,date:document.querySelector('#todoDate').value||'',notify:document.querySelector('#todoNotify').checked,createdAt:new Date().toISOString()});state=await saveState(state);await syncTodoNotifications();todoList(false)});
app.addEventListener('click',async e=>{const delCat=e.target.closest('[data-delete-category]');if(delCat){const cats=state.preferences.categories||[];cats.splice(Number(delCat.dataset.deleteCategory),1);state.preferences.categories=cats;state=await saveState(state);categorySettings();return}if(e.target.id==='exportBackup'){await exportBackup();return}const filter=e.target.closest('[data-filter]');if(filter){state.preferences.moneyFilters={...(state.preferences.moneyFilters||{}),[filter.dataset.filter]:filter.dataset.value};state=await saveState(state);flow(filter.dataset.filter);return}const prev=e.target.closest('[data-month-prev]');if(prev){const k=prev.dataset.monthPrev;flowMonths[k]=addMonths(flowMonths[k],-1);flow(k);return}const next=e.target.closest('[data-month-next]');if(next){const k=next.dataset.monthNext;flowMonths[k]=addMonths(flowMonths[k],1);flow(k);return}const addMoney=e.target.closest('[data-add-money]');if(addMoney){moneyForm(addMoney.dataset.addMoney);return}const moneyDone=e.target.closest('[data-money-done]');if(moneyDone){const i=state.entries.findIndex(x=>x.id===moneyDone.dataset.moneyDone);if(i>=0){const [x]=state.entries.splice(i,1);x.completedAt=new Date().toISOString();state.history.unshift(x);state.balance=realBalance()+(x.kind==='income'?Number(x.amount):-Number(x.amount));state=await saveState(state);flow(x.kind)}return}const complete=e.target.closest('[data-complete]');if(complete){const i=state.todo.tasks.findIndex(x=>x.id===complete.dataset.complete);if(i>=0){const [x]=state.todo.tasks.splice(i,1);x.completedAt=new Date().toISOString();state.todo.done.unshift(x);state=await saveState(state);await syncTodoNotifications();todoList(false)}return}const restore=e.target.closest('[data-restore]');if(restore){const i=state.todo.done.findIndex(x=>x.id===restore.dataset.restore);if(i>=0){const [x]=state.todo.done.splice(i,1);delete x.completedAt;state.todo.tasks.unshift(x);state=await saveState(state);await syncTodoNotifications();todoList(true)}return}const go=e.target.closest('[data-go]');if(go)return route(go.dataset.go);if(e.target.id==='editBudget'){const v=prompt('Budget totale del mese');if(v===null)return;const n=Number(v.replace(',','.'));if(Number.isFinite(n)&&n>=0){const ym=monthKey(),plans=state.budgetPlans||(state.budgetPlans=[]),i=plans.findIndex(x=>x.month===ym);const p={month:ym,total:n,limits:i>=0?plans[i].limits||{}:{}};if(i>=0)plans[i]=p;else plans.push(p);state=await saveState(state);budget()}return}if(e.target.id==='setBalance'){const v=prompt('Saldo reale attuale',String(realBalance()));if(v===null)return;const n=Number(v.replace(',','.'));if(Number.isFinite(n)){state.balance=n;state=await saveState(state);money()}}});
route('landing');
