import assert from 'node:assert/strict';
import { parseItalianAmount,parseItalianDate,parseItalianTime,parseItalianRecurrence,parseItalianVoiceEntry } from '../v2/voice.js';
import { formatDateValue, matchesDateFilter, matchesMonth, dateSortKey } from '../v2/date-values.js';
import { realBalance, projectedBalance, monthEndBalance, financeTotals, markCompleted, undoCompletion, deleteMoneyRecord, adjustCompletedAmount } from '../v2/finance.js';
import { generateOccurrenceDates, migrateLegacyRecurrences } from '../v2/recurrence.js';
import { collectNotificationPlan } from '../v2/notifications.js';
const monthly=generateOccurrenceDates('2024-01-31','day',{unit:'month',interval:1,end:'count',count:4});
assert.deepEqual(monthly.map(x=>x.date),['2024-01-31','2024-02-29','2024-03-31','2024-04-30']);
const weekly=generateOccurrenceDates('2026-01-05','day',{unit:'week',interval:2,end:'count',count:3});
assert.deepEqual(weekly.map(x=>x.date),['2026-01-05','2026-01-19','2026-02-02']);
const till=generateOccurrenceDates('2026-01-01','day',{unit:'month',interval:1,end:'date',until:'2026-03-01'});
assert.deepEqual(till.map(x=>x.date),['2026-01-01','2026-02-01','2026-03-01']);
const state={entries:[{id:'a',kind:'income',recurrence:'monthly',date:'2026-01-01'},{id:'b',kind:'income',recurrenceSource:'a',date:'2026-02-01'}],history:[],todo:{tasks:[{id:'t',recurrence:'weekly',date:'2026-01-01'}],done:[]}};
migrateLegacyRecurrences(state);
assert.equal(state.entries[1].seriesId,'a');assert.equal(state.todo.tasks[0].seriesId,'t');
const now=new Date('2026-01-01T00:00:00');
const plan=collectNotificationPlan({financeNotifications:{enabled:true,defaultTime:'09:00'},entries:[{id:'f',kind:'income',description:'Entrata',date:'',reminder:{enabled:true,mode:'custom',customAt:'2026-01-02T10:00'}}],todo:{notifications:{enabled:true,rule:{time:'08:00',advanceMinutes:0},dailySummary:true,dailySummaryTime:'18:00'},tasks:[{id:'t',description:'Attività',date:'2026-01-02',datePrecision:'day',reminder:{enabled:true,mode:'due',time:'08:30'}}]}},now);
assert.ok(plan.some(x=>x.extra.kind==='finance'&&x.title.includes('Conti')),'custom finance reminder works without due date');
assert.ok(plan.some(x=>x.extra.kind==='todo'&&x.title.includes('Attività')),'todo reminder is independently planned');
assert.ok(plan.some(x=>x.extra.kind==='todo-daily'),'daily summary coexists with finance and task notices');
console.log('PASS recurrence intervals/clamping/end dates, additive series migration, custom no-date reminders, independent notification channels and daily summary');

const recurringFinance={balance:500,entries:[...Array.from({length:18},(_,i)=>({id:`salary-${i}`,kind:'income',amount:1100,date:`${2026+Math.floor((9+i)/12)}-${String((9+i)%12+1).padStart(2,'0')}-10`,seriesId:'salary-series',occurrenceIndex:i})),...Array.from({length:18},(_,i)=>({id:`rent-${i}`,kind:'expense',amount:200,date:`${2026+Math.floor((9+i)/12)}-${String((9+i)%12+1).padStart(2,'0')}-15`,seriesId:'rent-series',occurrenceIndex:i})),{id:'one-off',kind:'income',amount:50,date:'2026-12-01'}],history:[]};
assert.equal(realBalance(recurringFinance),500,'future recurring entries never change the real balance');
assert.deepEqual(financeTotals(recurringFinance,'income','2026-10'),{pending:1100,done:0,total:1100},'October totals count one monthly salary, not all generated future occurrences');
assert.deepEqual(financeTotals(recurringFinance,'expense','2026-10'),{pending:200,done:0,total:200},'October totals count one recurring rent');
assert.equal(monthEndBalance(recurringFinance,'2026-10'),1400,'end of month is real balance plus only selected-month pending operations');
assert.equal(monthEndBalance(recurringFinance,'2026-11'),1400,'month switch scopes pending recurring entries');
assert.equal(projectedBalance(recurringFinance),1450,'overall forecast uses one-offs plus the next pending instance per recurring series');
assert.deepEqual(financeTotals(recurringFinance,'income','2027-01'),{pending:1100,done:0,total:1100},'recurrences keep the same monthly amount in later months');
const transaction={balance:100,entries:[{id:'in',kind:'income',amount:25,date:'2026-10-01'},{id:'out',kind:'expense',amount:10,date:'2026-10-02'}],history:[]};
assert.equal(markCompleted(transaction,'in','2026-10-03T10:00:00Z').amount,25);assert.equal(realBalance(transaction),125,'received income changes real balance once');assert.equal(markCompleted(transaction,'in'),null,'duplicate receipt is rejected');
assert.equal(markCompleted(transaction,'out','2026-10-04T10:00:00Z').amount,10);assert.equal(realBalance(transaction),115,'paid expense reduces real balance once');
assert.equal(undoCompletion(transaction,'out').id,'out');assert.equal(realBalance(transaction),125,'undo reverses a payment once');assert.equal(undoCompletion(transaction,'out'),null,'second undo is rejected');
transaction.entries.find(x=>x.id==='out').amount=12;assert.equal(realBalance(transaction),125,'editing a pending payment does not change real balance');
assert.equal(deleteMoneyRecord(transaction,'out'),true);assert.equal(realBalance(transaction),125,'deleting a pending payment does not change real balance');
const booked={balance:125,entries:[],history:[{id:'paid',kind:'expense',amount:20,date:'2026-10-02',completedAt:'2026-10-02T10:00:00Z'}]};
assert.equal(deleteMoneyRecord(booked,'paid'),true);assert.equal(realBalance(booked),145,'deleting a booked operation reverses its balance effect once');assert.equal(deleteMoneyRecord(booked,'paid'),false);assert.equal(realBalance(booked),145,'repeated delete cannot double reverse');
const adjusted={balance:125,entries:[],history:[{id:'adjust',kind:'income',amount:25,date:'2026-10-01'}]};adjustCompletedAmount(adjusted,25,30);adjusted.history[0].amount=30;assert.equal(realBalance(adjusted),130,'editing a completed amount applies only the difference');
const duplicate={balance:100,entries:[{id:'x',kind:'income',amount:10,date:'2026-10-01'}],history:[{id:'x',kind:'income',amount:10,date:'2026-10-01'}]};
assert.equal(projectedBalance(duplicate),100);assert.deepEqual(financeTotals(duplicate,'income','2026-10'),{pending:0,done:10,total:10});
const recurrence={balance:50,entries:[{id:'r1',kind:'expense',amount:20,date:'2026-10-01',seriesId:'r'},{id:'r2',kind:'expense',amount:20,date:'2026-11-01',seriesId:'r'}],history:[]};
assert.equal(projectedBalance(recurrence),30,'forecast includes one upcoming occurrence per recurring expense series');
assert.equal(monthEndBalance(recurrence,'2026-10'),30);assert.equal(monthEndBalance(recurrence,'2026-11'),30);
const undated={balance:40,entries:[{id:'no-date',kind:'income',amount:900,date:'',datePrecision:'none'},{id:'year-only',kind:'income',amount:800,date:'2026',datePrecision:'year'}],history:[]};assert.deepEqual(financeTotals(undated,'income','2026-10'),{pending:0,done:0,total:0},'undated or year-only records are not assigned to an arbitrary month');assert.equal(monthEndBalance(undated,'2026-10'),40);assert.equal(projectedBalance(undated),840,'a no-date operation is not treated as a dated forecast item');

assert.equal(formatDateValue('2026-10-09','day'),'9 ottobre 2026');
assert.equal(formatDateValue('10','monthOnly'),'ottobre');
assert.equal(formatDateValue('10-09','dayMonth'),'9 ottobre');
assert.equal(formatDateValue('2026','year'),'2026');
assert.equal(matchesMonth({date:'10',datePrecision:'monthOnly'},'2026-10'),true);
assert.equal(matchesMonth({date:'2026',datePrecision:'year'},'2026-10'),true);
assert.equal(matchesMonth({date:'2026-11',datePrecision:'month'},'2026-10'),false);
assert.equal(matchesDateFilter({date:'10-09',datePrecision:'dayMonth'},'10','2026'),true);
assert.equal(matchesDateFilter({date:'10',datePrecision:'monthOnly'},'09','2026'),false);
assert.ok(dateSortKey({date:'2026-10-09',datePrecision:'day'})>dateSortKey({date:'2026-10',datePrecision:'month'}));
assert.deepEqual(generateOccurrenceDates('2026','year',{unit:'year',interval:1,end:'count',count:3}),[{date:'2026',index:0},{date:'2027',index:1},{date:'2028',index:2}]);
assert.deepEqual(generateOccurrenceDates('10-09','dayMonth',{unit:'year',interval:1,end:'count',count:3}),[{date:'10-09',index:0}]);
const partialNotify={financeNotifications:{enabled:true},entries:[{id:'partial',kind:'income',date:'2026-10',datePrecision:'month',reminder:{enabled:true}},{id:'exact',kind:'income',date:'2026-10-09',datePrecision:'day',reminder:{enabled:true}}],todo:{notifications:{enabled:true},tasks:[{id:'partialTask',date:'10-09',datePrecision:'dayMonth',reminder:{enabled:true}}]}};
assert.deepEqual(collectNotificationPlan(partialNotify,new Date('2026-10-01T00:00:00')).map(x=>x.extra.itemId),['exact']);

assert.equal(parseItalianAmount('mille e cento euro'),1100);
assert.equal(parseItalianAmount('1.100,50 euro'),1100.5);
assert.equal(parseItalianAmount('centoventi'),120);
assert.deepEqual(parseItalianRecurrence('tutti i mesi'),{unit:'month',interval:1,end:'never'});
assert.deepEqual(parseItalianRecurrence('ogni 2 settimane'),{unit:'week',interval:2,end:'never'});
assert.equal(parseItalianTime('alle 10'),'10:00');assert.equal(parseItalianTime('10:35'),'10:35');assert.equal(parseItalianTime('alle dieci e trenta'),'10:30');
const spokenSalary=parseItalianVoiceEntry('Stipendio 1.100 euro il 10 ottobre, tutti i mesi',{kind:'income'});
assert.equal(spokenSalary.fields.description,'Stipendio');assert.equal(spokenSalary.fields.amount,1100);assert.equal(spokenSalary.fields.date,'2026-10-10');assert.equal(spokenSalary.fields.datePrecision,'day');assert.deepEqual(spokenSalary.fields.recurrenceRule,{unit:'month',interval:1,end:'never'});assert.deepEqual(spokenSalary.missing,[]);
const spokenSalaryWithoutComma=parseItalianVoiceEntry('Stipendio 1100 euro il 10 ottobre di ogni mese',{kind:'income'});assert.equal(spokenSalaryWithoutComma.fields.description,'Stipendio');assert.equal(spokenSalaryWithoutComma.fields.amount,1100);assert.equal(spokenSalaryWithoutComma.fields.date,'2026-10-10');assert.equal(spokenSalaryWithoutComma.fields.recurrenceRule.unit,'month');assert.deepEqual(spokenSalaryWithoutComma.missing,[]);
const spokenPartial=parseItalianVoiceEntry('Stipendio il 10 ottobre',{kind:'income'});assert.equal(spokenPartial.fields.date,'10-10');assert.equal(spokenPartial.fields.datePrecision,'dayMonth');assert.equal(spokenPartial.fields.amount,null);assert.deepEqual(spokenPartial.missing,['amount']);
const spokenTodo=parseItalianVoiceEntry('Chiamare il medico domani alle 10',{kind:'todo'});assert.equal(spokenTodo.fields.description,'Chiamare il medico');assert.equal(spokenTodo.fields.datePrecision,'day');assert.equal(spokenTodo.fields.time,'10:00');assert.equal(spokenTodo.fields.amount,null);
assert.deepEqual(parseItalianDate('9 ottobre 2026','day'),{suffix:'Date',value:'2026-10-09'});
assert.equal(parseItalianDate('31 febbraio 2026','day'),null,'voice date parsing rejects impossible calendar dates');
assert.deepEqual(parseItalianDate('9 ottobre','dayMonth'),{suffixes:['DayMonthMonth','DayMonthPart'],values:['10','9']});
assert.deepEqual(parseItalianDate('ottobre 2026','month'),{suffix:'Month',value:'2026-10'});
assert.equal(parseItalianDate('9 ottobre','day'),null);
